[package]
name = "cpivlr"
version = "0.1.0"
edition = "2021"

[dependencies]
cvlr = "0.4"
cvlr-solana = "0.4"
solana-program = "1.18"
spl-token = { version = "4", features = ["no-entrypoint"] }
spl-token-2022 = { version = "3", features = ["no-entrypoint"] }
